name: CI/CD Pipeline with Prometheus Monitoring

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Prometheus Service avec configuration par défaut
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build Docker image for Flask
      run: |
        docker build -t flask-app:latest .

    - name: Run Flask container
      run: |
        docker run -d -p 5000:5000 flask-app:latest

    - name: Test Flask API
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"tenure": 5, "MonthlyCharges": 70, "TotalCharges": 350}' http://localhost:5000/predict

    - name: Prometheus Metrics Test
      run: |
        curl http://localhost:9090/api/v1/query?query=up
