name: CI/CD Pipeline for Flask Churn Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker using official GitHub Action
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t flask-churn-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name flask-churn-app flask-churn-app

    - name: Wait for Flask to be ready
      run: |
        sleep 20  # Attendre que le serveur Flask soit prêt

    - name: Test Flask API
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"Age": 42, "Total_Purchase": 11066.80, "Account_Manager": 0, "Years": 7.22, "Num_Sites": 8}' \
        http://localhost:8000/predict

    - name: Check Prometheus metrics
      run: |
        curl http://localhost:8000/metrics

    - name: Clean up Docker container
      run: |
        docker stop flask-churn-app
        docker rm flask-churn-app
